openapi: 3.0.0
info:
  description: "API system"
  version: "1.0.0"
  title: "BACKEND API"
servers:
  - url: http://localhost:4466
    description: Remote server
tags:
- name: "user"
  description: "Access to User"

paths:
  /user/{id}:
    delete:
      tags:
        - "user"
      summary: "Delete user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to delete"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    get:
      tags:
        - "user"
      summary: "Get user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

  /user:
    get:
      tags:
        - "user"
      summary: "Get all users"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - "user"
      summary: "Create new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        201:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    put:
      tags:
        - "user"
      summary: "Update user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    



components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
          default: "user"
          enum:
            - "user"
            - "admin"
            - "menager"
    UserCreate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    BadRequest:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          default: 400
        
