openapi: 3.0.0
info:
  description: "API system"
  version: "1.0.1"
  title: "BACKEND API 2"
servers:
  - url: http://0.0.0.0:4466
    description: Remote server
tags:
- name: "auth"
  description: "Access to Auth"
- name: "user"
  description: "Access to User"


paths:
  /auth/login:
    get:
      tags:
        - "auth"
      summary: "Login user"
      security:
        - basicAuth: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokenization'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  
  /auth/check_token:
    get:
      tags:
        - "auth"
      summary: "Check token user"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'  
  /auth/refresh_token:
    get:
      tags:
        - "auth"
      summary: "Refresh token user"
      security:
        - bearerRefreshAuth: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/Tokenization'
            
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'   
    
  /user/{id}:
    delete:
      tags:
        - "user"
      summary: "Delete user by id"
      security:
        - bearerAuth: []
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to delete"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    get:
      tags:
        - "user"
      summary: "Get user by id"
      security:
        - bearerAuth: []
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

  /user:
    get:
      tags:
        - "user"
      summary: "Get all users"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - "user"
      summary: "Create new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        201:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    put:
      tags:
        - "user"
      summary: "Update user"
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    



components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT Authorization header using the Bearer scheme."
    bearerRefreshAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Tokenization:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
          default: "user"
          enum:
            - "user"
            - "admin"
            - "menager"
    UserCreate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    BadRequest:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          default: 400
        
